Repository APP-iOS4/ANBD, pull requests merged in 2024-05, with the labels that each got.

#347 design: Alert 및 Error 문구 수정
  ANBDConsumer/ANBDConsumer/Common/Util/UserStore.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Article/View/ArticleDetailView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Article/ViewModel/ArticleViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Authentication/ViewModel/AuthenticationViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Chat/ViewModel/ChatViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Home/ViewModel/HomeViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Report/ViewModel/ReportViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Trade/ViewModel/TradeViewModel.swift
Labels: design

#351 refactor: 신고하기 placeholder 수정
  ANBDConsumer/ANBDConsumer/Presentaion/Report/View/ReportView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Report/ViewModel/ReportViewModel.swift
Labels: refactor

#353 refactor: 채팅방에 사용자 차단하기 버튼 추가
  ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/ChatDetailView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
Labels: refactor

#356 feat: 채팅방 사용자 차단 기능 구현
  ANBDConsumer/ANBDConsumer/Presentaion/Chat/View/ChatDetailView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Chat/ViewModel/ChatViewModel.swift
Labels: feature

#358 feat: 사용자 정보 페이지에서 사용자 차단하기 기능 추가
  ANBDConsumer/ANBDConsumer.xcodeproj/project.pbxproj
  ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
  ANBDConsumer/ANBDConsumer/Presentaion/CommonUI/View/CustomAlertView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/BlockingUserListView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/SettingsView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
  ANBDModel/Sources/Data/DataSource/UserDataSource.swift
Labels: feature

#360 feat: 사용자 차단기능 - 거래글
  ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
Labels: feature

#363 refactor: 마이페이지 기타 기능 수정
  ANBDConsumer/ANBDConsumer/Common/Util/Coordinator.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/SettingsView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserActivityListView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
Labels: refactor

#366 refactor: 사용자 차단하기 Toast 문구 수정
  ANBDConsumer/ANBDConsumer/Presentaion/Article/View/ArticleDetailView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Article/ViewModel/ArticleViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/BlockingUserListView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/View/UserPageView.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Mypage/ViewModel/MyPageViewModel.swift
  ANBDConsumer/ANBDConsumer/Presentaion/Trade/View/TradeDetailView.swift
Labels: refactor

#368 fix: trade 필터링 시 not-in, in을 같이 사용해서 충돌나는 것 해결
  ANBDModel/Sources/Data/DataSource/PostDataSource.swift
Labels: bug
